### ISSUE TITLE
Link do artigo.

### ISSUE THREAD

**Issue by devsnaked** [armandobs14/mobilidade-urbana-mcz#1]
O link https://medium.com/@armandobs14/utilizando-dados-abertos-e-ci%C3%AAncia-de-dados-na-mobilidade-urbana não leva para o artigo.

**Comment by armandobs14** [comment]
acabei de atualizar  o link do artigo para https://medium.com/@armandobs14/utilizando-dados-abertos-e-ciência-de-dados-na-mobilidade-urbana-371a4c591639
